export interface TenagaPendidik {
  no: number;
  nama: string;
  jk: string;
  nuptk: string;
  jenisKelamin: string;
  statusPerkawinan: string;
  jabatanMapel: string;
  tamatanTahunGelar: string;
  tempatTanggalLahir: string;
  agama: string;
  alamat: string;
  email: string;
  jurusan: string;
  ijazahTahun: string;
  noSertifikatPendidik: string;
  tmt: string;
  jenjang: string;
  jurusan2: string;
}

export const data: TenagaPendidik[] = [
  {
    no: 1,
    nama: "HENDRA SAHPUTRA BATUBARA, S.Pd, M.Pd.T",
    jk: "L",
    nuptk: "4.3557626632E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "KEPALA SEKOLAH",
    tamatanTahunGelar: "2016",
    tempatTanggalLahir: "BELAWAN, 23 OKTOBER 1984",
    agama: "ISLAM",
    alamat: "JL. TM. PAHLAWAN GUDANG ARANG LR. SUPIR",
    email: "hendrabatubara46@gmail.com",
    jurusan: "MAGISTER PENDIDIKAN TEKNIK ELEKTRO",
    ijazahTahun: "2016",
    noSertifikatPendidik: "1021867303222",
    tmt: "2008-07-14",
    jenjang: "S2",
    jurusan2: "MAGISTER PENDIDIKAN TEKNIK ELEKTRO",
  },
  {
    no: 2,
    nama: "HUZAIMAH ULFA, S.Pd",
    jk: "P",
    nuptk: "1.7537626642101E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "WAKA KURIKULUM/KIMIA",
    tamatanTahunGelar: "2009",
    tempatTanggalLahir: "MEDAN, 21 APRIL 1984",
    agama: "ISLAM",
    alamat: "JL. MAGNOLIA 1 NO. 28 GRIYA MARTUBUNG III",
    email: "huzaimahulf4@gmail.com",
    jurusan: "PEND.KIMIA",
    ijazahTahun: "2009",
    noSertifikatPendidik: "10392018720167",
    tmt: "2009-07-01",
    jenjang: "S1",
    jurusan2: "PEND.KIMIA",
  },
  {
    no: 3,
    nama: "NURLI INDRA SARI, ST",
    jk: "L",
    nuptk: "4.4527606611301E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "WAKA HUBIN/PRODUKTIF TKJ",
    tamatanTahunGelar: "2010",
    tempatTanggalLahir: "MEDAN, 1 JANUARI 1982",
    agama: "ISLAM",
    alamat: "JL. KELADI NO. 42 LK XXII",
    email: "mybebyone@gmail.com",
    jurusan: "INFORMATIKA",
    ijazahTahun: "2010",
    noSertifikatPendidik: "",
    tmt: "2013-07-17",
    jenjang: "S1",
    jurusan2: "INFORMATIKA",
  },
  {
    no: 4,
    nama: "NURSYAHRUL RITONGA,ST,M.Pd",
    jk: "L",
    nuptk: "6.1367606612302E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PEND. AGAMA ISLAM",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "JANJI MANAHAN, 04 AGUSTUS 1982",
    agama: "ISLAM",
    alamat: "JL. MARELAN RAYA PASAR I REL GG.KELUARGA",
    email: "syahrulritonga0301@gmail.com",
    jurusan: "PEND.AGAMA ISLAM",
    ijazahTahun: "2019",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S2",
    jurusan2: "PEND.AGAMA ISLAM",
  },
  {
    no: 5,
    nama: "NURIS FADHLI SILANGIT, ST",
    jk: "L",
    nuptk: "6.7607626642E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF TKJ",
    tamatanTahunGelar: "2008",
    tempatTanggalLahir: "MEDAN/28 APRIL 1984",
    agama: "ISLAM",
    alamat: "JL. SAKTI LUBIS GG. KELUARGA NO. 38 H SIMPANG LIMUN",
    email: "langit606@gmail.com",
    jurusan: "TEKNIK KOMPUTER",
    ijazahTahun: "2008",
    noSertifikatPendidik: "1091733003361",
    tmt: "2012-07-01",
    jenjang: "S1",
    jurusan2: "TEKNIK KOMPUTER",
  },
  {
    no: 6,
    nama: "BUDI CAHYA, ST",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTOMOTIF",
    tamatanTahunGelar: "2018",
    tempatTanggalLahir: "BANDAR TINGGI/ 15 MARET 1995",
    agama: "ISLAM",
    alamat: "JL.PERJUANGAN TJ. SELAMAT SUNGGGAL",
    email: "cahyabudi072@gmail.com",
    jurusan: "TEKNIK MESIN",
    ijazahTahun: "2018",
    noSertifikatPendidik: "",
    tmt: "2018-07-20",
    jenjang: "S1",
    jurusan2: "TEKNIK MESIN",
  },
  {
    no: 7,
    nama: "AL ARIEF, S.Pd",
    jk: "L",
    nuptk: "3.6357686691301E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF LISTRIK",
    tamatanTahunGelar: "2013",
    tempatTanggalLahir: "BINJAI/ 3 MARET 1990",
    agama: "ISLAM",
    alamat: "JL. DATUK BAKAR NO. 6 BINJAI",
    email: "fmahardika23@gmail.com",
    jurusan: "TEKNIK ELEKTRO",
    ijazahTahun: "2013",
    noSertifikatPendidik: "",
    tmt: "2015-08-11",
    jenjang: "S1",
    jurusan2: "TEKNIK ELEKTRO",
  },
  {
    no: 8,
    nama: "ELFRIDA DORNA SIBURIAN, S.Pd",
    jk: "P",
    nuptk: "5.4347716721301E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP",
    tamatanTahunGelar: "2017",
    tempatTanggalLahir: "SILAGA LAGA, 02 NOVEMBER 1993",
    agama: "KRISTEN",
    alamat: "JL. PUYUH XIV NO 252 PERUMNAS MANDALA",
    email: "elfridaburian@gmail.com",
    jurusan: "PEND.EKONOMI",
    ijazahTahun: "2017",
    noSertifikatPendidik: "10332285624296",
    tmt: "2017-01-07",
    jenjang: "S1",
    jurusan2: "PEND.EKONOMI",
  },
  {
    no: 9,
    nama: "ASRI DELIWATI, S.Pd",
    jk: "P",
    nuptk: "9.33777167213E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/BIMBINGAN KONSELING",
    tamatanTahunGelar: "2015",
    tempatTanggalLahir: "MEDAN/ 5 OKTOBER 1993",
    agama: "ISLAM",
    alamat: "JL. MAWAR II BLOK III NO 236 PERUMNAS HELVETIA",
    email: "asrideliwati1993@gmail.com",
    jurusan: "BIMBINGAN KONSELING",
    ijazahTahun: "2015",
    noSertifikatPendidik: "",
    tmt: "2015-07-13",
    jenjang: "S1",
    jurusan2: "BIMBINGAN KONSELING",
  },
  {
    no: 10,
    nama: "KHAIRANI SITUMORANG, S.Pd",
    jk: "P",
    nuptk: "5.73577567623E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "BIMBINGAN KONSELING",
    tamatanTahunGelar: "2018",
    tempatTanggalLahir: "MEDAN/ 03 APRIL 1997",
    agama: "ISLAM",
    alamat: "JL. TUAMANG GG.KASAN NO.1 A",
    email: "khairanisitumorang323@yahoo.com",
    jurusan: "BIMBINGAN KONSELING",
    ijazahTahun: "2018",
    noSertifikatPendidik: "",
    tmt: "2019-07-15",
    jenjang: "S1",
    jurusan2: "BIMBINGAN KONSELING",
  },
  {
    no: 11,
    nama: "HUSNUL KHATIMAH, S.Pd",
    jk: "P",
    nuptk: "9.7357696701301E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "BIMBINGAN KONSELING",
    tamatanTahunGelar: "2013",
    tempatTanggalLahir: "SEI BAHARU/3 APRIL 1991",
    agama: "ISLAM",
    alamat: "DUSUN V SEI BAHARU HAMPARAN PERAK",
    email: "husnulkhatimah3491@gmail.com",
    jurusan: "BIMBINGAN KONSELING",
    ijazahTahun: "2013",
    noSertifikatPendidik: "",
    tmt: "2014-07-14",
    jenjang: "S1",
    jurusan2: "BIMBINGAN KONSELING",
  },
  {
    no: 12,
    nama: "SITI AMINAH PARINDURI, SE",
    jk: "P",
    nuptk: "3.45277167213E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "Ka. TATA USAHA",
    tamatanTahunGelar: "2015",
    tempatTanggalLahir: "MEDAN/ 20 JANUARI 1993",
    agama: "ISLAM",
    alamat: "JL. KARYA SUKADAMAI NO. 7 MEDAN",
    email: "parinduriaminah20@gmail.com",
    jurusan: "EKONOMI",
    ijazahTahun: "2015",
    noSertifikatPendidik: "",
    tmt: "2016-07-18",
    jenjang: "S1",
    jurusan2: "EKONOMI",
  },
  {
    no: 13,
    nama: "SABRINA KHAIRUNNISA, SE",
    jk: "P",
    nuptk: "5.8357716722302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "TATA USAHA",
    tamatanTahunGelar: "2016",
    tempatTanggalLahir: "MEDAN/3 MEI 1993",
    agama: "ISLAM",
    alamat: "JL. SAKTI LUBIS GG. KELUARGA NO. 38 H SIMPANG LIMUN",
    email: "sabrinarina75@gmail.com",
    jurusan: "MANAJEMEN",
    ijazahTahun: "2016",
    noSertifikatPendidik: "",
    tmt: "2019-07-15",
    jenjang: "S1",
    jurusan2: "MANAJEMEN",
  },
  {
    no: 14,
    nama: "KIKI HARDIYANTI, S.Kom",
    jk: "P",
    nuptk: "1.2367646653001E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "TATA USAHA",
    tamatanTahunGelar: "2018",
    tempatTanggalLahir: "MEDAN 08 MARET 1996",
    agama: "ISLAM",
    alamat: "JL. GARU IV NO.20 MEDAN AMPLAS",
    email: "kikihardiyanti83@gmail.com",
    jurusan: "KOMPUTER",
    ijazahTahun: "2018",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "KOMPUTER",
  },
  {
    no: 15,
    nama: "IBING HERMAWAN PURNOMO, S.Pd",
    jk: "L",
    nuptk: "6.1447726731301E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "BENDAHARA/GURU BAHASA INDONESIA",
    tamatanTahunGelar: "2017",
    tempatTanggalLahir: "MEDAN/12 AGUSTUS 1994",
    agama: "ISLAM",
    alamat: "JL.JALAN KEPRIBADIAN GG.BHAKTI NO. 3 MEDAN",
    email: "ibinghermawanpurnomo@gmail.com",
    jurusan: "PEND.BHS.INDONESIA",
    ijazahTahun: "2017",
    noSertifikatPendidik: "",
    tmt: "2017-07-17",
    jenjang: "S1",
    jurusan2: "PEND.BHS.INDONESIA",
  },
  {
    no: 16,
    nama: "NURJANAH, S.Pd",
    jk: "P",
    nuptk: "7.5497626633001E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PKN",
    tamatanTahunGelar: "2007",
    tempatTanggalLahir: "MEDAN/ 17 FEBRUARI 1984",
    agama: "ISLAM",
    alamat: "JL. PANCING GG. RUKUN INDRA KASIH",
    email: "", // Email not provided in the data
    jurusan: "PKN",
    ijazahTahun: "2007",
    noSertifikatPendidik: "1021515400850",
    tmt: "2005-07-01",
    jenjang: "S1",
    jurusan2: "PKN",
  },
  {
    no: 17,
    nama: "Dra. ROTUA MARPAUNG",
    jk: "P",
    nuptk: "1.9397436413E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PEND. AGAMA KRISTEN",
    tamatanTahunGelar: "1995",
    tempatTanggalLahir: "PORSEA/ 7 JUNI 1963",
    agama: "KRISTEN",
    alamat: "JL. PASAR III GG. KELUARGA NO. 16F MEDAN PERJUANGAN",
    email: "rotuamarpaung0@gmail.com",
    jurusan: "PEND.AGAMA KRISTEN",
    ijazahTahun: "1995",
    noSertifikatPendidik: "",
    tmt: "2012-07-01",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA KRISTEN",
  },
  {
    no: 18,
    nama: "DEWI BAHRIANA, S.Pd",
    jk: "P",
    nuptk: "4.4497636643E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PKN",
    tamatanTahunGelar: "2007",
    tempatTanggalLahir: "SEI SENTOSA/ 17 NOVEMBER 1985",
    agama: "ISLAM",
    alamat: "JL. HELVETIA BYPASS GG. SIGANTANG NO. 20",
    email: "dewibahriana85@gmail.com",
    jurusan: "PKN",
    ijazahTahun: "2007",
    noSertifikatPendidik: "1021315403605",
    tmt: "2005-08-01",
    jenjang: "S1",
    jurusan2: "PKN",
  },
  {
    no: 19,
    nama: "KURNIATI SURYA NINGSIH, S.Pd",
    jk: "P",
    nuptk: "6.4407616622101E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/FISIKA",
    tamatanTahunGelar: "2009",
    tempatTanggalLahir: "MEDAN/8 JANUARI 1983",
    agama: "ISLAM",
    alamat: "JL. LUKAH GG.KELUARGA NO.35 B MEDAN AMPLAS",
    email: "kurniatisuryaningsihspd@gmail.com",
    jurusan: "FISIKA",
    ijazahTahun: "2009",
    noSertifikatPendidik: "10112318421609",
    tmt: "2015-07-01",
    jenjang: "S1",
    jurusan2: "FISIKA",
  },
  {
    no: 20,
    nama: "YULFAH AZLINA MUNTHE, S.Pd",
    jk: "P",
    nuptk: "6.5676566613014E+14",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/SEJARAH INDONESIA",
    tamatanTahunGelar: "2012",
    tempatTanggalLahir: "KAMPUNG GEROJOKAN/ 24 MARET 1987",
    agama: "ISLAM",
    alamat: "DUSUN VII JL. VETERAN GG. LESTARI HELVETIA",
    email: "Yulfahazlina123@gmail.com",
    jurusan: "PEND.SEJARAH",
    ijazahTahun: "2012",
    noSertifikatPendidik: "",
    tmt: "2013-07-18",
    jenjang: "S1",
    jurusan2: "PEND.SEJARAH",
  },
  {
    no: 21,
    nama: "SUWITRI,S.Kom",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF TKJ",
    tamatanTahunGelar: "2017",
    tempatTanggalLahir: "MEDAN, 06 JUNI 1995",
    agama: "ISLAM",
    alamat: "JL.RUMAH POTONG HEWAN LINK.III MABAR HILIR",
    email: "switri06@gmail.com",
    jurusan: "ILMU KOMPUTER",
    ijazahTahun: "2017",
    noSertifikatPendidik: "",
    tmt: "2017-01-07",
    jenjang: "S1",
    jurusan2: "ILMU KOMPUTER",
  },
  {
    no: 22,
    nama: "HAMDAN LUTHFI SIHOMBING, S.Pd",
    jk: "L",
    nuptk: "8.8467656613302E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PENJASKES",
    tamatanTahunGelar: "2013",
    tempatTanggalLahir: "PASAR SORKAM/ 14 MEI 1987",
    agama: "ISLAM",
    alamat: "JL. MAWAR II BLOK III NO 236 PERUMNAS HELVETIA",
    email: "hamdansiho17@gmail.com",
    jurusan: "PENJASKES",
    ijazahTahun: "2013",
    noSertifikatPendidik: "",
    tmt: "2010-07-12",
    jenjang: "S1",
    jurusan2: "PENJASKES",
  },
  {
    no: 23,
    nama: "YOLANDA ELIZA, S.Pd",
    jk: "P",
    nuptk: "7.4417636641302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/MATEMATIKA",
    tamatanTahunGelar: "2015",
    tempatTanggalLahir: "MEDAN/ 20 AGUSTUS 1993",
    agama: "ISLAM",
    alamat: "JL. RAWE IV LK. IX MARTUBUNG",
    email: "yolandaeliza372@gmail.com",
    jurusan: "PEND. MATEMATIKA",
    ijazahTahun: "2015",
    noSertifikatPendidik: "",
    tmt: "2015-01-05",
    jenjang: "S1",
    jurusan2: "PEND. MATEMATIKA",
  },
  {
    no: 24,
    nama: "RIZKY ATIKA SARI, S.Pd",
    jk: "P",
    nuptk: "5.33577067123E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "GURU/BAHASA INGGRIS",
    tamatanTahunGelar: "2015",
    tempatTanggalLahir: "RANTAU LABAN/ 3 OKTOBER 1992",
    agama: "ISLAM",
    alamat: "JL. MEDAN BINJAI KM.16 PERUMAHAN BUKIT MAS BLOK A NO.28",
    email: "kikyatikaa@gmail.com",
    jurusan: "PEND.BHS.INGGRIS",
    ijazahTahun: "2015",
    noSertifikatPendidik: "10402115720617",
    tmt: "2015-07-14",
    jenjang: "S1",
    jurusan2: "PEND.BHS.INGGRIS",
  },
  {
    no: 25,
    nama: "SHERLY ADRILA FITRI, M.Pd",
    jk: "P",
    nuptk: "2.8367686692302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/MATEMATIKA",
    tamatanTahunGelar: "2016",
    tempatTanggalLahir: "PAINAN, 04 MEI 1990",
    agama: "ISLAM",
    alamat: "JL. BENTENG HILIR PERUMAHAN GRIYA BENTENG ASRI BLOK B NO. 2",
    email: "sherlyadrila46@gmail.com",
    jurusan: "MATEMATIKA",
    ijazahTahun: "2016",
    noSertifikatPendidik: "",
    tmt: "2014-07-14",
    jenjang: "S2",
    jurusan2: "MATEMATIKA",
  },
  {
    no: 26,
    nama: "NABILA KHODIJAH, S.Pd",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "MATEMATIKA",
    tamatanTahunGelar: "2022",
    tempatTanggalLahir: "MEDAN, 25 OKTOBER 2000",
    agama: "ISLAM",
    alamat: "JL. RAWA 1 LR. SEDAR NO.25",
    email: "nabilakhodijah233@gmail.com",
    jurusan: "MATEMATIKA",
    ijazahTahun: "2022",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "MATEMATIKA",
  },
  {
    no: 27,
    nama: "JAMIL MISTIKA, S.Pd",
    jk: "L",
    nuptk: "3.9487616622E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PENJASKES",
    tamatanTahunGelar: "2007",
    tempatTanggalLahir: "MEDAN/ 16 JUNI 1983",
    agama: "ISLAM",
    alamat: "JL. KEPRIBADIAN NO. 6 PULO BRAYAN BENGKEL",
    email: "jamilnaza16@gmail.com",
    jurusan: "PENJASKES",
    ijazahTahun: "2007",
    noSertifikatPendidik: "1021422005784",
    tmt: "2007-08-02",
    jenjang: "S1",
    jurusan2: "PENJASKES",
  },
  {
    no: 28,
    nama: "MALINAR NASUTION, S.Kom",
    jk: "P",
    nuptk: "7.54777167213E+14",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PRODUKTIF TKJ",
    tamatanTahunGelar: "2006",
    tempatTanggalLahir: "SENTRAL/ 16 DESEMBER 1993",
    agama: "ISLAM",
    alamat: "JL. DURUNG III ANDAN SARI KEL. TERJUN",
    email: "nasution1612@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2006",
    noSertifikatPendidik: "",
    tmt: "2015-07-15",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 29,
    nama: "NENI SUPRIANI, S.Si,M.M",
    jk: "P",
    nuptk: "6.8457696702302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/KIMIA",
    tamatanTahunGelar: "2021",
    tempatTanggalLahir: "MEDAN/ 13 MEI 1991",
    agama: "ISLAM",
    alamat: "JL. KARYA BAKTI NO. 51 MEDAN",
    email: "nenisupriani484@gmail.com",
    jurusan: "MANAJEMEN PENDIDIKAN",
    ijazahTahun: "2021",
    noSertifikatPendidik: "",
    tmt: "2015-07-23",
    jenjang: "S2",
    jurusan2: "MANAJEMEN PENDIDIKAN",
  },
  {
    no: 30,
    nama: "MITA YUNITA SARI, S.Pd",
    jk: "P",
    nuptk: "1.2447676682301E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/BAHASA INGGRIS",
    tamatanTahunGelar: "2012",
    tempatTanggalLahir: "JOMBANG/ 21 SEPTEMBER 1989",
    agama: "ISLAM",
    alamat: "JL. MARELAN III PASAR III BARAT LK. IV GG. TANI NO. 15",
    email: "mitayunitasari229@gmail.com",
    jurusan: "PEND.BHS.INGGRIS",
    ijazahTahun: "2012",
    noSertifikatPendidik: "10402015720630",
    tmt: "2013-07-18",
    jenjang: "S1",
    jurusan2: "PEND.BHS.INGGRIS",
  },
  {
    no: 31,
    nama: "DWI MAHARTIKA, S.Pd, M.A",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/BAHASA INGGRIS",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "MEDAN/ 5 JANUARI 1995",
    agama: "ISLAM",
    alamat: "JL. SEHATI GG. SABARUDDIN NO. 6 MEDAN",
    email: "dwimahartika95@gmail.com",
    jurusan: "BHS.INGGRIS",
    ijazahTahun: "2019",
    noSertifikatPendidik: "",
    tmt: "2017-07-24",
    jenjang: "S2",
    jurusan2: "BHS.INGGRIS",
  },
  {
    no: 32,
    nama: "SANDY ARMANDO SAPUTRA, S.Pd",
    jk: "L",
    nuptk: "6.54977267313E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF LISTRIK",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "MARKANDING/ 17 DESEMBER 1994",
    agama: "ISLAM",
    alamat: "JL. DAHLIA NO.43 MEDAN TEMBUNG",
    email: "sandyarmandosaputra@ymail.com",
    jurusan: "TEKNIK ELEKTRO",
    ijazahTahun: "2019",
    noSertifikatPendidik: "10402341320593",
    tmt: "2015-07-25",
    jenjang: "S1",
    jurusan2: "TEKNIK ELEKTRO",
  },
  {
    no: 33,
    nama: "WIDIA NINGSIH, S.Pd",
    jk: "P",
    nuptk: "1.2367646653001E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "BAHASA INDONESIA",
    tamatanTahunGelar: "2009",
    tempatTanggalLahir: "CINTA RAKYAT/ 4 SEPTEMBER 1986",
    agama: "ISLAM",
    alamat: "JL. TRUNOJOYO NO. 16 DUSUN XI CINTA RAKYAT",
    email: "widyaningsih123ww@gmail.com",
    jurusan: "PEND.BHS.INGGRIS",
    ijazahTahun: "2009",
    noSertifikatPendidik: "1021515600883",
    tmt: "2016-07-18",
    jenjang: "S1",
    jurusan2: "PEND.BHS.INDONESIA",
  },
  {
    no: 34,
    nama: "SANTI UTAMI, S.Pd",
    jk: "P",
    nuptk: "7.4417636641302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "BAHASA INDONESIA",
    tamatanTahunGelar: "2009",
    tempatTanggalLahir: "KOLAM/ 9 JANUARI 1985",
    agama: "ISLAM",
    alamat: "JL. UTAMA II DESA KOLAM NO. 63",
    email: "santiutami985@gmail.com",
    jurusan: "PEND.BHS.INDONESIA",
    ijazahTahun: "2009",
    noSertifikatPendidik: "",
    tmt: "2012-07-01",
    jenjang: "S1",
    jurusan2: "PEND.BHS.INDONESIA",
  },
  {
    no: 35,
    nama: "INGGIT HANNALIS HARDI TARINI ARIMBI, ST",
    jk: "P",
    nuptk: "7.5457726732301E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF TKJ",
    tamatanTahunGelar: "2017",
    tempatTanggalLahir: "MEDAN/ 13 DESEMBER 1994",
    agama: "ISLAM",
    alamat: "JL. UTAMA GG. SOSIAL NO.12 B",
    email: "ibyarimbhie4898@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2017",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 36,
    nama: "NURUL FADHILLAH, S.Kom",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF TKJ",
    tamatanTahunGelar: "2023",
    tempatTanggalLahir: "MEDAN, 17 AGUSTUS 2000",
    agama: "ISLAM",
    alamat: "JL. KEMIRI 3 SIMPANG LIMUN",
    email: "nuurull.f@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2023",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 37,
    nama: "IRFAN GUSNAIDI, ST",
    jk: "L",
    nuptk: "8.1357536562E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTOMOTIF",
    tamatanTahunGelar: "2001",
    tempatTanggalLahir: "MEDAN/ 3 AGUSTUS 1975",
    agama: "ISLAM",
    alamat: "JL. LAKSANA NO. 16 E MEDAN",
    email: "Gusnaidiirfan472@gmail.com",
    jurusan: "TEKNIK OTOMOTIF",
    ijazahTahun: "2001",
    noSertifikatPendidik: "",
    tmt: "2011-08-01",
    jenjang: "S1",
    jurusan2: "TEKNIK OTOMOTIF",
  },
  {
    no: 39,
    nama: "NISSA ARISTANTYA, S.Pd.I",
    jk: "P",
    nuptk: "4.8417726732301E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "MATEMATIKA",
    tamatanTahunGelar: "2016",
    tempatTanggalLahir: "MEDAN/ 09 MEI 1994",
    agama: "ISLAM",
    alamat: "JL.MANGAAN 1 LINK. XIX MABAR, GG.BAHAGIA II",
    email: "nissaaristantiya2012@gmail.com",
    jurusan: "PEND.MATEMATIKA",
    ijazahTahun: "2016",
    noSertifikatPendidik: "",
    tmt: "2016-07-18",
    jenjang: "S1",
    jurusan2: "MATEMATIKA",
  },
  {
    no: 40,
    nama: "ERFINA WATI SIMAMORA, S.Kom",
    jk: "P",
    nuptk: "6.2507636642302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PRODUKTIF TKJ",
    tamatanTahunGelar: "2012",
    tempatTanggalLahir: "MEDAN/18 SEPTEMBER 1985",
    agama: "KRISTEN",
    alamat: "JL. SMRAJA GG.P HARAPAN NO.36",
    email: "erfinawati1011@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2012",
    noSertifikatPendidik: "",
    tmt: "2019-07-15",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 41,
    nama: "M. NABARISYAH TANJUNG, S.Kom",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "TOOLMAN TKJ",
    tamatanTahunGelar: "2021",
    tempatTanggalLahir: "MEDAN/ 18 NOVEMBER 1998",
    agama: "ISLAM",
    alamat: "JL. WILLIAM ISKANDAR NO. 47",
    email: "yugabari5@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2021",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 42,
    nama: "UMMY KALSUM ASP, S.Pd",
    jk: "P",
    nuptk: "8.8477706712302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU PIKET",
    tamatanTahunGelar: "2015",
    tempatTanggalLahir: "MEDAN/ 15 MEI 1992",
    agama: "ISLAM",
    alamat: "JL. SETIA LUHUR GG. ROTAN",
    email: "ambar.parlindungan28@gmail.com",
    jurusan: "BIMBINGAN KONSELING",
    ijazahTahun: "2015",
    noSertifikatPendidik: "",
    tmt: "2016-07-18",
    jenjang: "S1",
    jurusan2: "BIMBINGAN KONSELING",
  },
  {
    no: 43,
    nama: "DERU AMARU KURNIAWAN, ST",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "TOOLMAN OTOMOTIF",
    tamatanTahunGelar: "S1/MASIH AKTIF",
    tempatTanggalLahir: "MEDAN/ 30 OKTOBER 1998",
    agama: "ISLAM",
    alamat: "JL. VETERAN PASAR VII HELVETIA",
    email: "deruamarukurniawan@gmail.com",
    jurusan: "TEKNIK OTOMOTIF",
    ijazahTahun: "S1/MASIH AKTIF",
    noSertifikatPendidik: "",
    tmt: "2016-07-18",
    jenjang: "S1",
    jurusan2: "TEKNIK OTOMOTIF",
  },
  {
    no: 44,
    nama: "ZOELKARNAIN RINANDA T, S.Pd, M.Kom",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF TITL",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "TANJUNG PURA/05 JUNI 1991",
    agama: "ISLAM",
    alamat: "JL. KENANGA PERUM.KAMPOENG KENANGA BLOK H NO.14 BATANG KUIS",
    email: "zoelkarnaintembusai@gmail.com",
    jurusan: "MAGISTER TEKNIK INFORMATIKA",
    ijazahTahun: "2019",
    noSertifikatPendidik: "",
    tmt: "2018-07-20",
    jenjang: "S1",
    jurusan2: "MAGISTER TEKNIK INFORMATIKA",
  },
  {
    no: 45,
    nama: "ABDUL RAHIM",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/PRODUKTIF OTOMOTIF",
    tamatanTahunGelar: "1998",
    tempatTanggalLahir: "PEMATANG SIANTAR/06 JANUARI 1966",
    agama: "ISLAM",
    alamat: "JL.MANGGAAN IV LINGK.2 MABAR HILIR MEDAN",
    email: "abdulrahim123562@gmail.com",
    jurusan: "ADM.OTOMOTIF",
    ijazahTahun: "1998",
    noSertifikatPendidik: "",
    tmt: "2019-07-15",
    jenjang: "S2",
    jurusan2: "ADM.OTOMOTIF",
  },
  {
    no: 46,
    nama: "EBENEZER SIMANGUNSONG, S.Kom",
    jk: "L",
    nuptk: "4.5777367413009E+14",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF TKJ",
    tamatanTahunGelar: "2017",
    tempatTanggalLahir: "PORSEA, 25 NOVEMBER 1995",
    agama: "KRISTEN",
    alamat: "JL.TUNGGUK UTAMA III BLOK 3 NO.242 GRIYA MARTUBUNG",
    email: "benezer147@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2017",
    noSertifikatPendidik: "",
    tmt: "2019-07-15",
    jenjang: "D3",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 47,
    nama: "M NURSABDIN, ST",
    jk: "L",
    nuptk: "2.9617746751301E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF OTOMOTIF",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "SEI MATI, 29 JUNI 1996",
    agama: "ISLAM",
    alamat: "BATANG KILAT LINK II KELURAHAN SEI MATI",
    email: "muhammadnursabdin@gmail.com",
    jurusan: "TEKNIK OTOMOTIF",
    ijazahTahun: "2019",
    noSertifikatPendidik: "",
    tmt: "2019-07-15",
    jenjang: "S1",
    jurusan2: "TEKNIK OTOMOTIF",
  },
  {
    no: 48,
    nama: "AYUB JAYAHADI KESUMA NURANDI, ST",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF OTOMOTIF",
    tamatanTahunGelar: "2023",
    tempatTanggalLahir: "LABUHAN DELI, 17 MARET 1998",
    agama: "ISLAM",
    alamat: "JL. YOUNG PANAH HIJAU LINK.VII GG.MAKMUR",
    email: "ayubkesuma17@gmail.com",
    jurusan: "TEKNIK OTOMOTIF",
    ijazahTahun: "2023",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "TEKNIK OTOMOTIF",
  },
  {
    no: 49,
    nama: "SITI ANISAH, S.Kom",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "GURU/PRODUKTIF TKJ",
    tamatanTahunGelar: "2020",
    tempatTanggalLahir: "BELAWAN, 16 JUNI 1997",
    agama: "ISLAM",
    alamat: "JL. TM. PAHLAWAN LORONG SUPIR GUDANG ARANG BELAWAN I",
    email: "anisabatubara12@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2020",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 50,
    nama: "MAULANA CHAIRIL",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "OPERATOR DAPODIK",
    tamatanTahunGelar: "S1/MASIH AKTIF",
    tempatTanggalLahir: "MARELAN, 04 JANUARI 1999",
    agama: "ISLAM",
    alamat: "JL. MARELAN RAYA PASAR 2 GG.INDAH",
    email: "malkonovalov4.ru@gmail.com",
    jurusan: "",
    ijazahTahun: "",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "",
  },
  {
    no: 51,
    nama: "LEO SARDO SITUMORANG, S.Pd",
    jk: "L",
    nuptk: "6.5075265420001E+14",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/BAHASA INGGRIS",
    tamatanTahunGelar: "2015",
    tempatTanggalLahir: "MEDAN, 18 MARET 1974",
    agama: "KRISTEN",
    alamat: "JL. BILAL UJUNG GG. RELA NO.248C",
    email: "tibositumorang@gmail.com",
    jurusan: "PEND.BHS.INGGRIS",
    ijazahTahun: "2015",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "SMA",
    jurusan2: "PEND.BHS.INGGRIS",
  },
  {
    no: 52,
    nama: "SRI ROZI ANGGRAINI, S.Pd.I",
    jk: "P",
    nuptk: "3.2567636642302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "GURU/AGAMA ISLAM",
    tamatanTahunGelar: "2012",
    tempatTanggalLahir: "PADANG, 24 SEPTEMBER 1985",
    agama: "ISLAM",
    alamat: "JL. PANCING 2 NO 17 C MEDAN TEMBUNG",
    email: "srirozi@gmail.com",
    jurusan: "PEND.AGAMA ISLAM",
    ijazahTahun: "2012",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA ISLAM",
  },
  {
    no: 53,
    nama: "WULANDARI AGUSTINA, S.Pd",
    jk: "P",
    nuptk: "4.1547736742301E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "BAHASA INDONESIA",
    tamatanTahunGelar: "2018",
    tempatTanggalLahir: "MEDAN, 22 AGUSTUS 1995",
    agama: "ISLAM",
    alamat: "JL. BERINGIN PASAR V TEMBUNG GG. SALAK 16 NO.17 PERCUT SEI TUAN",
    email: "awulandari821@gmail.com",
    jurusan: "PEND.BHS,INDONESIA",
    ijazahTahun: "2018",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "PEND.BHS,INDONESIA",
  },
  {
    no: 54,
    nama: "MAHMUD, M.Si",
    jk: "L",
    nuptk: "9.6387536552E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP",
    tamatanTahunGelar: "2020",
    tempatTanggalLahir: "PASAR BARU, 06 MARET 1975",
    agama: "ISLAM",
    alamat: "JL. PERHUBUNGAN DUSUN VIII MAWAR LAU DENDANG",
    email: "abdi_isanmadani@yahoo.co.id",
    jurusan: "ILMU EKONOMI",
    ijazahTahun: "2020",
    noSertifikatPendidik: "1061353903732",
    tmt: "2021-07-14",
    jenjang: "S2",
    jurusan2: "ILMU EKONOMI",
  },
  {
    no: 55,
    nama: "ADE JULIA NANDA, S.Pd",
    jk: "P",
    nuptk: "2.0437676682302E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP",
    tamatanTahunGelar: "2011",
    tempatTanggalLahir: "BINJAI, 11 JULI 1989",
    agama: "ISLAM",
    alamat: "JL. RAYA MENTENG GG.ABADI NO.15-A KEL.BINJAI KEC.MEDAN DENAI",
    email: "adejuliananda89@gmail.com",
    jurusan: "PEND.AKUNTANSI",
    ijazahTahun: "2011",
    noSertifikatPendidik: "",
    tmt: "2017-01-23",
    jenjang: "S1",
    jurusan2: "PEND.AKUNTANSI",
  },
  {
    no: 56,
    nama: "MURNIATY BR SITORUS",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "AGAMA KRISTEN",
    tamatanTahunGelar: "2018",
    tempatTanggalLahir: "MEDAN , 25 JANUARI 1996",
    agama: "KRISTEN",
    alamat: "JL. ELANG UJUNG NO.250",
    email: "", // Email not provided in the data
    jurusan: "PEND.AGAMA KRISTEN",
    ijazahTahun: "2018",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA KRISTEN",
  },
  {
    no: 57,
    nama: "ARIEF FATAHILLAH PRADANA MANULANG",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "TOOLMAN OTOMOTIF",
    tamatanTahunGelar: "SMK/2022",
    tempatTanggalLahir: "MEDAN, 05 SEPTEMBER 2004",
    agama: "ISLAM",
    alamat: "JL.SIDORUKUN",
    email: "", // Email not provided in the data
    jurusan: "",
    ijazahTahun: "SMK/2022",
    noSertifikatPendidik: "",
    tmt: "2022-07-18",
    jenjang: "S1",
    jurusan2: "",
  },
  {
    no: 58,
    nama: "MUNAYA ARMI, S.Pd",
    jk: "P",
    nuptk: "3.3376866913016E+14",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP",
    tamatanTahunGelar: "2013",
    tempatTanggalLahir: "HAMPARAN PERAK, 1 OKTOBER 1990",
    agama: "ISLAM",
    alamat: "DSN 1 SEI BAHARU KEC.HAMPARAN PERAK",
    email: "munayaarmi9009@gmail.com",
    jurusan: "PEND.EKONOMI",
    ijazahTahun: "2013",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "SMK",
    jurusan2: "PEND.EKONOMI",
  },
  {
    no: 59,
    nama: "LUTHFI NUGRAHA, STr.Bns",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP DAN AKL",
    tamatanTahunGelar: "2020",
    tempatTanggalLahir: "MEDAN, 8 DESEMBER 1998",
    agama: "ISLAM",
    alamat: "JL. SETIABUDI TANJUNG SARI PASAR 1 GG.MAWAR NO.6A MEDAN",
    email: "luthfinugraha00@gmail.com",
    jurusan: "AKUNTANSI PERBANKAN SYARIAH",
    ijazahTahun: "2020",
    noSertifikatPendidik: "",
    tmt: "2018-07-20",
    jenjang: "S1",
    jurusan2: "AKUNTANSI PERBANKAN SYARIAH",
  },
  {
    no: 60,
    nama: "SRI WAHYUNI, SE",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP DAN AKL",
    tamatanTahunGelar: "2020",
    tempatTanggalLahir: "MEDAN, 12 JUNI 1998",
    agama: "ISLAM",
    alamat: "JL. JATI GG.KELUARGA NO.93C KRAKATAU UJUNG MEDAN",
    email: "sriwahtuni1255@gmail.com",
    jurusan: "PERBANKAN SYARIAH",
    ijazahTahun: "2020",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "D4",
    jurusan2: "PERBANKAN SYARIAH",
  },
  {
    no: 61,
    nama: "MHD APRI MURDAYA",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "TOOLMAN TITL",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "PASAR BILAH, 06 APRIL 2001",
    agama: "ISLAM",
    alamat: "JL. MARELAN PASAR 2 BARAT GG. NANGKA",
    email: "mhdaprimurdaya@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2019",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 62,
    nama: "Dra. TENGKU SYAFRIANI",
    jk: "P",
    nuptk: "6.7557476493E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF TITL",
    tamatanTahunGelar: "1994",
    tempatTanggalLahir: "MEDAN, 23 APRIL 1969",
    agama: "ISLAM",
    alamat: "JL. MENTENG GG MESJID BAITURRAHMAN NO. 4 MEDAN",
    email: "tengkusyafriani@ymail.com",
    jurusan: "PEND.TEKNIK ELEKTRO",
    ijazahTahun: "1994",
    noSertifikatPendidik: "20741308412",
    tmt: "2022-07-18",
    jenjang: "S1",
    jurusan2: "PEND.TEKNIK ELEKTRO",
  },
  {
    no: 63,
    nama: "AYU DIAH SYAHFITRI, S.Pd",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "BAHASA INGGRIS",
    tamatanTahunGelar: "2021",
    tempatTanggalLahir: "Medan, 24 Oktober 1998",
    agama: "ISLAM",
    alamat: "JL. YOUNG PANAH HIJAU LORONG MELATI",
    email: "ayudiahsyahfitri28@gmail.com",
    jurusan: "PEND.BHS.INGGRIS",
    ijazahTahun: "2021",
    noSertifikatPendidik: "",
    tmt: "2021-07-14",
    jenjang: "S1",
    jurusan2: "PEND.BHS.INGGRIS",
  },
  {
    no: 64,
    nama: "ANASTASYA AULIA FITRI, S.Pd",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PRODUKTIF MULTI MEDIA",
    tamatanTahunGelar: "2022",
    tempatTanggalLahir: "MEDAN, 16 DESEMBER 2001",
    agama: "ISLAM",
    alamat: "JL. MARELAN V LINK 17 KELURAHAN RENGAS PULAU",
    email: "auliatasya12.12@gmail.com",
    jurusan: "TEKNIK INFORMATIKA",
    ijazahTahun: "2022",
    noSertifikatPendidik: "",
    tmt: "2023-01-16",
    jenjang: "S1",
    jurusan2: "TEKNIK INFORMATIKA",
  },
  {
    no: 65,
    nama: "MUHAMMAD IBNU SYAH, S.Pd.I",
    jk: "L",
    nuptk: "1.3517676691301E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PEND. AGAMA ISLAM",
    tamatanTahunGelar: "2014",
    tempatTanggalLahir: "Blankahan, 19 Oktober 1989",
    agama: "ISLAM",
    alamat: "Jl. KATES DUSUN III GRAND TAMAN PERMATA INDAH 2",
    email: "ibnu.syah77@gmail.com",
    jurusan: "PEND.AGAMA ISLAM",
    ijazahTahun: "2014",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA ISLAM",
  },
  {
    no: 66,
    nama: "ISRINA, S.Sn",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "SENI BUDAYA",
    tamatanTahunGelar: "2022",
    tempatTanggalLahir: "Muaro Sijunjung, 17 Juli 1999",
    agama: "ISLAM",
    alamat: "JL. BILAL UJUNG GG. DAHLIA",
    email: "isrina17@gmail.com",
    jurusan: "PEN.SENI TARI",
    ijazahTahun: "2022",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PEN.SENI TARI",
  },
  {
    no: 67,
    nama: "KHAIRUNNISA’ NABILAH, S.Pd",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "MATEMATIKA",
    tamatanTahunGelar: "2022",
    tempatTanggalLahir: "Medan, 29 Desember 2000",
    agama: "ISLAM",
    alamat: "JL. UMAR NO. 60",
    email: "nisa3899@gmail.com",
    jurusan: "PEND. MATEMATIKA",
    ijazahTahun: "2022",
    noSertifikatPendidik: "",
    tmt: "2023-07-24",
    jenjang: "S1",
    jurusan2: "PEND. MATEMATIKA",
  },
  {
    no: 68,
    nama: "KOMARIAH ANUM",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "TOOLMAN MULTIMEDIA",
    tamatanTahunGelar: "SMK/2023",
    tempatTanggalLahir: "Medan, 14 April 2005",
    agama: "ISLAM",
    alamat: "JL. MEDAN UTARA GG. SETIA BUDI",
    email: "komariahhanum2@gmail.com",
    jurusan: "",
    ijazahTahun: "2023",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "",
  },
  {
    no: 69,
    nama: "MASITAH, S.Pd",
    jk: "P",
    nuptk: "3.2357586592101E+15",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF OTKP DAN IPAS",
    tamatanTahunGelar: "2011",
    tempatTanggalLahir: "SELOTANG, 03 SEPTEMBER 1980",
    agama: "ISLAM",
    alamat: "JL. PASAR LAMA LINK. 29 PEKAN LABUHAN",
    email: "masitahrokan@gmail.com",
    jurusan: "PEND.EKONOMI",
    ijazahTahun: "2011",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "SMK",
    jurusan2: "PEND.EKONOMI",
  },
  {
    no: 70,
    nama: "YOGA PRATAMA, S.Pd",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PENJASKES",
    tamatanTahunGelar: "2019",
    tempatTanggalLahir: "MEDAN, 08 APRIL 1994",
    agama: "ISLAM",
    alamat: "JL.MADIRSAN GG DARMO TANJUNG MORAWA",
    email: "yogapratama1919@gmail.com",
    jurusan: "PENJASKES",
    ijazahTahun: "2019",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PENJASKES",
  },
  {
    no: 71,
    nama: "RASYID NUR SALAM, S.Pd",
    jk: "L",
    nuptk: "2.9347736741301E+15",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PRODUKTIF TBSM",
    tamatanTahunGelar: "2018",
    tempatTanggalLahir: "LANGSA, 02 JUNI 1995",
    agama: "ISLAM",
    alamat: "MARELAN PSR 4 BARAT",
    email: "rasyidnursalam@gmail.com",
    jurusan: "PEND. OTOMOTIF",
    ijazahTahun: "2018",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA ISLAM",
  },
  {
    no: 72,
    nama: "MUHAMMAD DAUD, S.Pd",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PEND.AGAMA ISLAM",
    tamatanTahunGelar: "2022",
    tempatTanggalLahir: "SARANG HELANG, 17 OKTOBER 1996",
    agama: "ISLAM",
    alamat: "KOMPLEK BENHIL 2, BENTENG HILIR, DESA BANDAR KHALIFAH",
    email: "daudmnr2@gmail.com",
    jurusan: "PEND.AGAMA ISLAM",
    ijazahTahun: "2022",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA ISLAM",
  },
  {
    no: 73,
    nama: "M. ASYRAF ALWI MAULANA SELIAN, SH",
    jk: "L",
    nuptk: "",
    jenisKelamin: "LAKI-LAKI",
    statusPerkawinan: "MENIKAH",
    jabatanMapel: "PEND.AGAMA ISLAM",
    tamatanTahunGelar: "2022",
    tempatTanggalLahir: "MEDAN, 30 JANUARI 2000",
    agama: "ISLAM",
    alamat: "JL. KEMENANGAN NO. 76.A",
    email: "Ashraf004alwi@gmail.com",
    jurusan: "PEND.AGAMA ISLAM",
    ijazahTahun: "2022",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PEND.AGAMA ISLAM",
  },
  {
    no: 74,
    nama: "HERFELINA PASARIBU",
    jk: "P",
    nuptk: "",
    jenisKelamin: "PEREMPUAN",
    statusPerkawinan: "BELUM MENIKAH",
    jabatanMapel: "PIKET",
    tamatanTahunGelar: "2023",
    tempatTanggalLahir: "ACEH, 2 MEI 2001",
    agama: "KRISTEN",
    alamat: "KOMPLEK TAMAN SEKATA INDAH",
    email: "pasaribuherfelina@gmail.com",
    jurusan: "PERTANIAN",
    ijazahTahun: "2023",
    noSertifikatPendidik: "",
    tmt: "2023-07-17",
    jenjang: "S1",
    jurusan2: "PERTANIAN",
  },
];
